version: '2.4'
services:
  iris:
    build: .
    restart: always
    command: --check-caps false
    ports:
      - 51773:1972
      - 52773:52773
      - 53773
    volumes:
#      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/iris/app
